INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Corbin', 'Sparrow', 'podkarpackie', 1987, 337500, 132000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.0, 405, 'manual', '4x4', 'brown', 'cabriolet', 'metallic', 'diesel', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('BMW', 'M6', 'lubelskie', 1980, 134000, 154250);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.3, 398, 'automatic', '4x4', 'graphite', 'liftback', 'pearl', 'ethanol', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('GMC', 'Savana 1500', 'wielkopolskie', 2002, 269000, 40500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.9, 316, 'manual', 'front', 'navy blue', 'dual cowl', 'nonmetallic', 'ethanol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Audi', '100', 'pomorskie', 2006, 252500, 30000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.2, 315, 'automatic', 'front', 'brown', 'roadster', 'nonmetallic', 'petrol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Lamborghini', 'Murciélago', 'œl¹skie', 2013, 347500, 13750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.6, 366, 'automatic', 'rear', 'black', 'limousine', 'metallic', 'petrol + LPG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Mercedes-Benz', 'CL-Class', 'wielkopolskie', 1996, 364500, 66750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.4, 294, 'automatic', 'rear', 'red', 'minivan', 'pearl', 'petrol + LPG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Nissan', '200SX', 'zachodniopomorskie', 1988, 298000, 86000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.6, 150, 'automatic', 'rear', 'black', 'SUV', 'nonmetallic', 'ethanol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Volvo', 'V50', 'zachodniopomorskie', 1987, 105500, 186500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.5, 364, 'automatic', '4x4', 'navy blue', 'van', 'mat', 'electric', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Mercedes-Benz', 'CL-Class', 'podkarpackie', 1987, 397500, 77000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.6, 103, 'automatic', '4x4', 'yellow', 'coupe', 'acrylic', 'diesel', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chevrolet', '3500', 'warmiñsko-mazurskie', 1980, 189000, 134000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.5, 424, 'manual', 'front', 'navy blue', 'coupe', 'pearl', 'hybrid', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Kia', 'Sorento', 'dolnoœl¹skie', 1981, 294000, 67750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.7, 65, 'automatic', 'rear', 'yellow', 'minivan', 'mat', 'petrol + LPG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Hyundai', 'Elantra', 'ma³opolskie', 2014, 380000, 42750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.9, 169, 'automatic', 'front', 'brown', 'liftback', 'mat', 'hydrogen', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Lexus', 'RX', 'warmiñsko-mazurskie', 1982, 209500, 151250);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.6, 319, 'automatic', 'front', 'black', 'pick-up', 'metallic', 'hybrid', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Cadillac', 'Fleetwood', '³ódzkie', 2010, 109500, 133250);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.6, 412, 'manual', 'rear', 'white', 'dual cowl', 'metallic', 'petrol + LPG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chevrolet', 'Express', 'warmiñsko-mazurskie', 2006, 252000, 100000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.2, 413, 'manual', 'rear', 'silver', 'liftback', 'metallic', 'hydrogen', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Porsche', 'Panamera', 'dolnoœl¹skie', 1999, 330000, 195000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(5.0, 57, 'manual', '4x4', 'gold', 'pick-up', 'pearl', 'petrol + LPG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Toyota', 'MR2', 'dolnoœl¹skie', 2005, 2500, 110750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.0, 388, 'automatic', 'rear', 'black', 'van', 'pearl', 'petrol', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Honda', 'del Sol', 'mazowieckie', 2006, 119500, 112750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.2, 129, 'manual', '4x4', 'black', 'liftback', 'pearl', 'diesel', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chrysler', 'Crossfire', 'warmiñsko-mazurskie', 2000, 191500, 34250);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.2, 448, 'automatic', 'rear', 'red', 'minivan', 'acrylic', 'hydrogen', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Mercedes-Benz', 'C-Class', 'warmiñsko-mazurskie', 1985, 372500, 193000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.0, 91, 'manual', 'front', 'yellow', 'targa', 'nonmetallic', 'diesel', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Ford', 'Ranger', 'œl¹skie', 1983, 232500, 127500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.9, 267, 'automatic', '4x4', 'grey', 'limousine', 'pearl', 'petrol', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Cadillac', 'Seville', 'dolnoœl¹skie', 2008, 57000, 132500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.5, 159, 'manual', 'front', 'silver', 'liftback', 'mat', 'ethanol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Mitsubishi', 'Mighty Max', 'lubelskie', 1984, 177000, 185000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.4, 381, 'automatic', '4x4', 'gold', 'limousine', 'pearl', 'hybrid', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('GMC', 'Canyon', '³ódzkie', 2005, 195000, 155500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.3, 437, 'automatic', 'front', 'green', 'cabriolet', 'nonmetallic', 'petrol + LPG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chevrolet', 'Classic', 'warmiñsko-mazurskie', 2012, 347500, 160500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.3, 181, 'automatic', '4x4', 'graphite', 'van', 'pearl', 'electric', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Isuzu', 'Trooper', 'mazowieckie', 1994, 121000, 103750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.0, 156, 'automatic', 'front', 'grey', 'pick-up', 'acrylic', 'ethanol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Infiniti', 'FX', 'dolnoœl¹skie', 2001, 322500, 107500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.3, 433, 'manual', '4x4', 'blue', 'fastback', 'acrylic', 'hybrid', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Pontiac', 'Firebird Trans Am', 'podlaskie', 2010, 91000, 184500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.1, 298, 'automatic', 'rear', 'navy blue', 'sedan', 'nonmetallic', 'ethanol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Buick', 'Regal', 'wielkopolskie', 1993, 288500, 60250);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.2, 472, 'automatic', '4x4', 'brown', 'microvan', 'pearl', 'petrol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chrysler', 'Cirrus', 'dolnoœl¹skie', 1989, 322500, 16500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.9, 421, 'manual', 'rear', 'grey', 'van', 'pearl', 'hydrogen', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chevrolet', 'Express', 'ma³opolskie', 2003, 268500, 147500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.1, 135, 'automatic', '4x4', 'yellow', 'targa', 'mat', 'diesel', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chevrolet', 'HHR', 'œl¹skie', 1985, 253500, 39750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.9, 156, 'manual', 'front', 'graphite', 'targa', 'mat', 'petrol + LPG', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('BMW', 'X5 M', '³ódzkie', 1994, 211000, 92500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.2, 264, 'automatic', 'rear', 'navy blue', 'combo', 'nonmetallic', 'ethanol', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Oldsmobile', 'Bravada', 'zachodniopomorskie', 1986, 115000, 18250);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.6, 81, 'automatic', '4x4', 'graphite', 'microvan', 'metallic', 'hybrid', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Volkswagen', 'Eurovan', 'lubuskie', 2000, 377000, 137000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.0, 455, 'automatic', 'front', 'white', 'liftback', 'metallic', 'petrol + CNG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Mazda', '626', 'œwiêtokrzyskie', 1982, 368500, 159500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.6, 165, 'manual', 'rear', 'navy blue', 'fastback', 'pearl', 'hydrogen', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Toyota', 'Supra', 'ma³opolskie', 1987, 352000, 17500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.0, 114, 'automatic', 'front', 'yellow', 'limousine', 'nonmetallic', 'diesel', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Nissan', '350Z', 'œwiêtokrzyskie', 2008, 146500, 169750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.4, 199, 'automatic', '4x4', 'red', 'minivan', 'nonmetallic', 'diesel', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Dodge', 'Caravan', 'pomorskie', 1980, 373000, 192500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.7, 99, 'automatic', 'front', 'navy blue', 'limousine', 'metallic', 'petrol', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chevrolet', 'S10', 'pomorskie', 2009, 258500, 193250);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(5.0, 135, 'automatic', 'front', 'gold', 'combo', 'acrylic', 'petrol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Chevrolet', 'Corvette', 'dolnoœl¹skie', 1982, 281500, 31750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.1, 129, 'automatic', '4x4', 'yellow', 'fastback', 'nonmetallic', 'petrol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Ford', 'Ranger', 'podkarpackie', 1999, 140500, 9750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.7, 362, 'automatic', 'rear', 'navy blue', 'dual cowl', 'pearl', 'diesel', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Bentley', 'Continental GTC', 'œl¹skie', 2004, 138500, 126500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.7, 428, 'automatic', 'front', 'green', 'targa', 'pearl', 'hybrid', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Pontiac', 'Grand Prix', 'dolnoœl¹skie', 2007, 361000, 132750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(3.7, 374, 'automatic', 'front', 'graphite', 'microvan', 'acrylic', 'petrol + LPG', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Kia', 'Spectra', 'podkarpackie', 1997, 248000, 51750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.1, 323, 'manual', '4x4', 'navy blue', 'sedan', 'acrylic', 'ethanol', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Kia', 'Amanti', 'lubuskie', 1997, 132000, 26750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.4, 51, 'automatic', 'front', 'graphite', 'fastback', 'mat', 'ethanol', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Buick', 'Lucerne', 'ma³opolskie', 2011, 21500, 7500);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(2.6, 339, 'automatic', 'front', 'navy blue', 'pick-up', 'mat', 'petrol + CNG', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Ford', 'Thunderbird', 'œl¹skie', 2002, 376000, 32750);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.6, 427, 'manual', 'rear', 'green', 'cabriolet', 'mat', 'petrol', '4/5');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Mercedes-Benz', 'S-Class', 'lubelskie', 2007, 310000, 195000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(4.1, 352, 'manual', 'front', 'red', 'microvan', 'acrylic', 'petrol + LPG', '2/3');
INSERT INTO car(car_brand, car_model, car_region, production_year, mileage, price) VALUES('Mercedes-Benz', 'E-Class', 'lubelskie', 1986, 286500, 34000);
INSERT INTO car_features(engine_capacity, engine_power, gearbox_type, car_drive,car_body_color, car_body_type, car_cover, fuel_type, number_of_doors) VALUES(1.1, 451, 'manual', 'rear', 'orange', 'microvan', 'nonmetallic', 'hybrid', '2/3');
