INSERT INTO client(full_name, client_type, company_name) VALUES('W³adys³aw Gawe³', 'company', 'First Trust Nasdaq Bank ETF');
INSERT INTO client(full_name, client_type, company_name) VALUES('Larysa Kozak', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Ksenia Wiêcek', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Zachariasz Górski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Gwido Krajewski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Szczepan Tracz', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Weronika Makowski', 'company', 'NB Capital Acquisition Corp.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Zygmunt Adamiec', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Porfiry Napiera³a', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Piotr Sobolewski', 'company', 'Partner Communications Company Ltd.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Daria Milczarek', 'company', 'Chuy&#39;s Holdings, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Anastazja Wyszyñski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Bruno Mróz', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Filip Balcerzak', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Krystian Borowiec', 'company', 'First Bancorp, Inc (ME)');
INSERT INTO client(full_name, client_type, company_name) VALUES('Innocenty Krupiñski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Porfiriusz Szwarc', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Maksym Gawron', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Eugeniusz Kasperek', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Samuel Jarosz', 'company', 'Intuitive Surgical, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Bernard Stanis³awski', 'company', 'Monster Beverage Corporation');
INSERT INTO client(full_name, client_type, company_name) VALUES('And¿elika Jarz¹bek', 'company', 'Biolase, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Wincenty GwóŸdŸ', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Hubert D¹bek', 'company', 'National Energy Services Reunited Corp.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Lilia Szczepaniak', 'company', 'Net 1 UEPS Technologies, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Romeo Stankiewicz', 'company', 'National Bankshares, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Benedykt Kowalczyk', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Aleksandra Rudzki', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Cyryl Fr¹tczak', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Aleksander Owczarek', 'company', 'Impax Laboratories, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Prokop Ciszewski', 'company', 'Legacy Reserves LP');
INSERT INTO client(full_name, client_type, company_name) VALUES('Walenty Skóra', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Ró¿a Murawski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Janusz Balcerzak', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Bertrand Wrona', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Alina Zió³kowski', 'company', 'Simmons First National Corporation');
INSERT INTO client(full_name, client_type, company_name) VALUES('Izabela Gruszczyñski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Maksym Gawe³', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Nazariusz Sowiñski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Janina Olejnik', 'company', 'The Ultimate Software Group, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Patrycja Rosiak', 'company', 'Cornerstone OnDemand, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Oliwia Stanek', 'company', 'Bridgeline Digital, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Walery Mierzejewski', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Lilla Szel¹g', 'company', 'Reading International Inc');
INSERT INTO client(full_name, client_type, company_name) VALUES('Ilona Kaczmarek', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Eleonora Urbaniak', 'individual', null);
INSERT INTO client(full_name, client_type, company_name) VALUES('Daria Herman', 'company', 'Farmers & Merchants Bancorp, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('Wilhelmina Witkowski', 'company', 'Haynes International, Inc.');
INSERT INTO client(full_name, client_type, company_name) VALUES('August Mucha', 'company', 'First Trust Large Cap Value AlphaDEX Fund');
INSERT INTO client(full_name, client_type, company_name) VALUES('Ofelia Sobczyk', 'individual', null);
