INSERT INTO seller(full_name, seller_type, company_name) VALUES('Kira Skrzypczak', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Hipolit Domaga³a', 'company', 'Duluth Holdings Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Maryna Kuliñski', 'company', 'Second Sight Medical Products, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Sabina Mroczkowski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Wanesa Chrzanowski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Konstantyn Chmura', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Hipolit Wojtasik', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Renata Konopka', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Maurycy Kapusta', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Walentyna Bogusz', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Modest Wójcicki', 'company', 'Harvest Capital Credit Corporation');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Gilbert Borowiec', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Maja D³ugosz', 'company', 'Playa Hotels & Resorts N.V.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Laurencja Piórkowski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Walery Wójcik', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Stefania Chmiel', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Beatrycze Karwowski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Helena Porêbski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Borys Niedziela', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Teodora Laskowski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Ludwik Rzepka', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Gracja Karaœ', 'company', 'S&T Bancorp, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Sabina Pietruszka', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Gedeon Pawlikowski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Malwina Kopczyñski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Ansgary Florek', 'company', 'Stein Mart, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Edward Mielczarek', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Wilhelm Urbaniak', 'company', 'Fidelity Southern Corporation');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Diana Prokop', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Edwin Czarnecki', 'company', 'CPS Technologies Corp.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Eliza Wi¹cek', 'company', 'Citizens Community Bancorp, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Jeremiasz Pietrzyk', 'company', 'Verisk Analytics, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Olimpia Dobrowolski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Oskar Muszyñski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Maja Radecki', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Micha³ WoŸniak', 'company', 'PowerShares DWA Healthcare Momentum Portfolio');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Cyrus Góra', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Innocenty Karaœ', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Reginald Pawlak', 'company', 'Sequential Brands Group, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Arkadiusz Markowski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Atanazy Zagórski', 'company', 'Discovery Communications, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Zachariasz Szostak', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Aurora Budziñski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Weronika Dêbowski', 'company', 'Onvia, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Archibald Wojciechowski', 'company', 'ICC Holdings, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Gonsalwy Œlusarczyk', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Monika Olejniczak', 'company', 'Inter Parfums, Inc.');
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Hubert Januszewski', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Wiktoria G¹sior', 'null', null);
INSERT INTO seller(full_name, seller_type, company_name) VALUES('Arkady ¯uk', 'company', 'Bellicum Pharmaceuticals, Inc.');
